# file_mdm_exif module schema

# Schema for settings.
file_mdm_exif.settings:
  type: config_object
  label: 'File metadata EXIF plugin settings'
  mapping:
    ifd_map:
      type: sequence
      sequence:
        type: file_mdm_exif.ifd
